[package]
name = "winapi_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
window = {path = "../window"}
application = {path = "../application"}
rand = "0.8.4"
smallvec = "1.6.1"
